# config/packages/easy_admin.yaml
easy_admin:
    entities:
        Movie:
            class: App\Entity\Movie
        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }