# config/packages/easy_admin.yaml
easy_admin:
    entities:

        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }


        Episode:
            class: App\Entity\Episode
            templates:
                edit: 'admin/videoSerie/edit.html.twig'
                new: 'admin/videoSerie/new.html.twig'


        Season:
            class: App\Entity\Season

        Serie:
            class: App\Entity\Serie
            form:
                fields:
                    - Name
                    - FirstReleased
                    - Plot
                    - Rating


        Movie :
            class : App\Entity\Movie
            templates:
                edit: 'admin/videoMovie/edit.html.twig'
                new: 'admin/videoMovie/new.html.twig'

