easy_admin:
    entities:

        Episode:
            class: App\Entity\Episode

        Season:
            class: App\Entity\Season

        Serie:
            class: App\Entity\Serie
            form:
                fields:
                    - Name
                    - FirstReleased
                    - Plot
                    - Rating
            templates:
                edit: 'admin/videoSerie/edit.html.twig'
                new: 'admin/videoSerie/new.html.twig'


        Movie :
            class : App\Entity\Movie
            templates:
                edit: 'admin/videoMovie/edit.html.twig'
                new: 'admin/videoMovie/new.html.twig'

