# config/packages/easy_admin.yaml
easy_admin:
    entities:

        User:
            class: App\Entity\User
            form:
                fields:
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }


        Episode:
            class: App\Entity\Episode

        Season:
            class: App\Entity\Season

        Serie:
            class: App\Entity\Serie
            form:
                fields:
                    - Name
                    - FirstReleased
                    - Plot
                    - Rating
                    - { property: 'season', type: 'easyadmin_autocomplete', type_options: { attr: { create: true } } }

        Movie :
            class : App\Entity\Movie
